# Generated by Django 4.2.5 on 2023-11-23 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kauacosta', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuarios',
            new_name='Usuario',
        ),
    ]
